sample_to_class: # processes and classes
    GGJets: is_non_resonant_bkg
    DDQCDGJET: is_non_resonant_bkg
    TTGG: is_non_resonant_bkg
    ttHtoGG_M_125: is_ttH_bkg
    # BBHto2G_M_125: is_single_H_bkg
    GluGluHToGG_M_125: is_single_H_bkg
    VBFHToGG_M_125: is_single_H_bkg
    VHtoGG_M_125: is_single_H_bkg
    GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00: is_GluGluToHH_sig

classes: # all classes
- is_non_resonant_bkg
- is_ttH_bkg
- is_single_H_bkg
- is_GluGluToHH_sig

weight_scheme_process: # how to weight each processes within a class
    # xsec : weight them according to the cross-section of each process
    # equal_weight: weight each process eqally, if there are two processes, you first weight the sum of each processes to be equal and then weight the whole class to be 1
    is_non_resonant_bkg: xsec 
    is_ttH_bkg: xsec
    is_single_H_bkg: xsec
    is_GluGluToHH_sig: xsec 

# some info for training
do_random_search: False
num_random_search: 1
weight_scheme: weighted_abs # weighted_only_positive # weighted_CRUW_abs # weighted_CRUW_only_positive
random_seed: 42
cuda_device: "0"

samples_info: 
    samples_path: /ceph/cms/store/user/jaguo/Run2HHbbgg/all_eras # samples path
    eras:
    - "2016APV"
    - "2016nonAPV"
    - "2017"
    - "2018"
    2016APV: # give relative path to
        GGJets: "Run2_2016APV/GGJets.parquet"
        DDQCDGJET: "Run2_2016APV/DDQCDGJets.parquet"
        TTGG: "Run2_2016APV/TTGG.parquet"
        ttHtoGG_M_125: "Run2_2016APV/ttHToGG.parquet"
        GluGluHToGG_M_125: "Run2_2016APV/GluGluHToGG.parquet"
        VBFHToGG_M_125: "Run2_2016APV/VBFHToGG.parquet"
        VHtoGG_M_125: "Run2_2016APV/VHToGG.parquet"
        GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00: "Run2_2016APV/GluGluToHH.parquet"
    2016nonAPV: # give relative path to
        GGJets: "Run2_2016nonAPV/GGJets.parquet"
        DDQCDGJET: "Run2_2016nonAPV/DDQCDGJets.parquet"
        TTGG: "Run2_2016nonAPV/TTGG.parquet"
        ttHtoGG_M_125: "Run2_2016nonAPV/ttHToGG.parquet"
        GluGluHToGG_M_125: "Run2_2016nonAPV/GluGluHToGG.parquet"
        VBFHToGG_M_125: "Run2_2016nonAPV/VBFHToGG.parquet"
        VHtoGG_M_125: "Run2_2016nonAPV/VHToGG.parquet"
        GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00: "Run2_2016nonAPV/GluGluToHH.parquet"
    "2017": # give relative path to
        GGJets: "Run2_2017/GGJets.parquet"
        DDQCDGJET: "Run2_2017/DDQCDGJets.parquet"
        TTGG: "Run2_2017/TTGG.parquet"
        ttHtoGG_M_125: "Run2_2017/ttHToGG.parquet"
        GluGluHToGG_M_125: "Run2_2017/GluGluHToGG.parquet"
        VBFHToGG_M_125: "Run2_2017/VBFHToGG.parquet"
        VHtoGG_M_125: "Run2_2017/VHToGG.parquet"
        GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00: "Run2_2017/GluGluToHH.parquet"
    "2018": # give relative path to
        GGJets: "Run2_2018/GGJets.parquet"
        DDQCDGJET: "Run2_2018/DDQCDGJets.parquet"
        TTGG: "Run2_2018/TTGG.parquet"
        ttHtoGG_M_125: "Run2_2018/ttHToGG.parquet"
        GluGluHToGG_M_125: "Run2_2018/GluGluHToGG.parquet"
        VBFHToGG_M_125: "Run2_2018/VBFHToGG.parquet"
        VHtoGG_M_125: "Run2_2018/VHToGG.parquet"
        GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00: "Run2_2018/GluGluToHH.parquet"
    data:
        2016APV: "Run2_2016APV/Data.parquet"
        2016nonAPV: "Run2_2016nonAPV/Data.parquet"
        "2017": "Run2_2017/Data.parquet"
        "2018": "Run2_2018/Data.parquet"

