mlp:
    vars:
    - eta
    - lead_eta
    - lead_phi
    - lead_mvaID
    - nonResReg_pholead_PtOverM
    - sublead_eta
    - sublead_phi
    - sublead_mvaID
    - nonResReg_phosublead_PtOverM
    - nonResReg_lead_bjet_eta
    - nonResReg_lead_bjet_phi
    - nonResReg_lead_bjet_btagPNetB
    - nonResReg_sublead_bjet_eta
    - nonResReg_sublead_bjet_phi
    - nonResReg_sublead_bjet_btagPNetB
    - nonResReg_DeltaR_j1g1
    - nonResReg_DeltaR_j2g1
    - nonResReg_DeltaR_j1g2
    - nonResReg_DeltaR_j2g2
    - nonResReg_DeltaR_jg_min
    - nonResReg_CosThetaStar_CS
    - nonResReg_CosThetaStar_gg
    - nonResReg_CosThetaStar_jj
    - puppiMET_phi
    - puppiMET_pt
    - n_leptons
    - n_jets
    - nonResReg_chi_t0
    - nonResReg_chi_t1
    - nonResReg_DeltaPhi_j1MET
    - nonResReg_DeltaPhi_j2MET
    - VBF_first_jet_eta
    - VBF_first_jet_phi
    - VBF_second_jet_eta
    - VBF_second_jet_phi
    - VBF_first_jet_PtOverM
    - VBF_second_jet_PtOverM
    - VBF_jet_eta_prod
    - VBF_jet_eta_diff
    - VBF_jet_eta_sum
    - VBF_DeltaR_j1b1
    - VBF_DeltaR_j1b2
    - VBF_DeltaR_j2b1
    - VBF_DeltaR_j2b2
    - VBF_DeltaR_j1g1
    - VBF_DeltaR_j1g2
    - VBF_DeltaR_j2g1
    - VBF_DeltaR_j2g2
    - VBF_DeltaR_jb_min
    - VBF_DeltaR_jg_min
    - VBF_dijet_mass
    - nonResReg_HHbbggCandidate_eta
    
    # variables added at preparation level which are not available in HiggsDNA output
    - diphoton_PtOverM_ggjj
    - nonResReg_dijet_PtOverM_ggjj
    - deltaR_gg
    - nonResReg_lead_bjet_over_M_regressed
    - nonResReg_sublead_bjet_over_M_regressed
