sample_to_class: # processes and classes
    GGJets: is_non_resonant_bkg
    DDQCDGJET: is_non_resonant_bkg
    TTGG: is_non_resonant_bkg
    ttHtoGG_M_125: is_ttH_bkg
    BBHto2G_M_125: is_single_H_bkg
    GluGluHToGG_M_125: is_single_H_bkg
    VBFHToGG_M_125: is_single_H_bkg
    VHtoGG_M_125: is_single_H_bkg
    GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00: is_GluGluToHH_sig

classes: # all classes
- is_non_resonant_bkg
- is_ttH_bkg
- is_single_H_bkg
- is_GluGluToHH_sig

weight_scheme_process: # how to weight each processes within a class
    # xsec : weight them according to the cross-section of each process
    # equal_weight: weight each process eqally, if there are two processes, you first weight the sum of each processes to be equal and then weight the whole class to be 1
    is_non_resonant_bkg: xsec 
    is_ttH_bkg: xsec
    is_single_H_bkg: xsec
    is_GluGluToHH_sig: xsec 

# some info for training
do_random_search: False
num_random_search: 1
weight_scheme: weighted_abs # weighted_only_positive # weighted_CRUW_abs # weighted_CRUW_only_positive
random_seed: 42
cuda_device: "0"

samples_info: 
    samples_path: /eos/cms/store/group/phys_b2g/HHbbgg/HiggsDNA_parquet/v3/ # samples path
    eras:
    - preEE
    - postEE
    - preBPix
    - postBPix
    preEE: # give relative path to
        GGJets: "Run3_2022/sim/preEE/DDQCDGJets/GGJets_high_Rescaled.parquet"
        DDQCDGJET: "Run3_2022/sim/preEE/DDQCDGJets/DDQCDGJET_Rescaled.parquet"
        TTGG: "Run3_2022/sim/preEE/TTGG/nominal/NOTAG_merged.parquet" 
        ttHtoGG_M_125: "Run3_2022/sim/preEE/ttHtoGG/nominal/NOTAG_merged.parquet"
        BBHto2G_M_125: "Run3_2022/sim/preEE/bbHtoGG/nominal/NOTAG_merged.parquet"
        GluGluHToGG_M_125: "Run3_2022/sim/preEE/GluGluHtoGG/nominal/NOTAG_merged.parquet"
        VBFHToGG_M_125: "Run3_2022/sim/preEE/VBFHtoGG/nominal/NOTAG_merged.parquet"
        VHtoGG_M_125: "Run3_2022/sim/preEE/VHtoGG/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00: "Run3_2022/sim/preEE/GluGlutoHH_kl-1p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_5p00_kt_1p00_c2_0p00: "Run3_2022/sim/preEE/GluGlutoHH_kl-5p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_0p00_kt_1p00_c2_0p00: "Run3_2022/sim/preEE/GluGlutoHH_kl-0p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_2p45_kt_1p00_c2_0p00: "Run3_2022/sim/preEE/GluGlutoHH_kl-2p45_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        # TTG_10_100: "Run3_2022/sim/preEE/TTG-1Jets_PTG-10to100.parquet"
        TTG_100_200: "Run3_2022/sim/preEE/TTG-1Jets_PTG-100to200/nominal/NOTAG_merged.parquet"
        TTG_200: "Run3_2022/sim/preEE/TTG-1Jets_PTG-200/nominal/NOTAG_merged.parquet"
        # TT: "Run3_2022/sim/preEE/TT.parquet"
    postEE:
        GGJets: "Run3_2022/sim/postEE/DDQCDGJets/GGJets_high_Rescaled.parquet"
        DDQCDGJET: "Run3_2022/sim/postEE/DDQCDGJets/DDQCDGJET_Rescaled.parquet"
        TTGG: "Run3_2022/sim/postEE/TTGG/nominal/NOTAG_merged.parquet"
        ttHtoGG_M_125: "Run3_2022/sim/postEE/ttHToGG/nominal/NOTAG_merged.parquet"
        BBHto2G_M_125: "Run3_2022/sim/postEE/bbHtoGG/nominal/NOTAG_merged.parquet"
        GluGluHToGG_M_125: "Run3_2022/sim/postEE/GluGluHtoGG/nominal/NOTAG_merged.parquet"
        VBFHToGG_M_125: "Run3_2022/sim/postEE/VBFHToGG/nominal/NOTAG_merged.parquet"
        VHtoGG_M_125: "Run3_2022/sim/postEE/VHtoGG/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00: "Run3_2022/sim/postEE/GluGlutoHH_kl-1p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_5p00_kt_1p00_c2_0p00: "Run3_2022/sim/postEE/GluGlutoHH_kl-5p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_0p00_kt_1p00_c2_0p00: "Run3_2022/sim/postEE/GluGlutoHH_kl-0p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_2p45_kt_1p00_c2_0p00: "Run3_2022/sim/postEE/GluGlutoHH_kl-2p45_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        # TTG_10_100: "Run3_2022/sim/postEE/TTG-1Jets_PTG-10to100.parquet"
        TTG_100_200: "Run3_2022/sim/postEE/TTG-1Jets_PTG-100to200/nominal/NOTAG_merged.parquet"
        TTG_200: "Run3_2022/sim/postEE/TTG-1Jets_PTG-200/nominal/NOTAG_merged.parquet"
        # TT: "Run3_2022/sim/postEE/TT.parquet"
    preBPix:
        GGJets: "Run3_2023/sim/preBPix/DDQCDGJets/GGJets_high_Rescaled.parquet"
        DDQCDGJET: "Run3_2023/sim/preBPix/DDQCDGJets/DDQCDGJET_Rescaled.parquet"
        TTGG: "Run3_2023/sim/preBPix/TTGG/nominal/NOTAG_merged.parquet"
        ttHtoGG_M_125: "Run3_2023/sim/preBPix/ttHtoGG/nominal/NOTAG_merged.parquet"
        BBHto2G_M_125: "Run3_2023/sim/preBPix/bbHtoGG/nominal/NOTAG_merged.parquet"
        GluGluHToGG_M_125: "Run3_2023/sim/preBPix/GluGluHtoGG/nominal/NOTAG_merged.parquet"
        VBFHToGG_M_125: "Run3_2023/sim/preBPix/VBFHtoGG/nominal/NOTAG_merged.parquet"
        VHtoGG_M_125: "Run3_2023/sim/preBPix/VHtoGG/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00: "Run3_2023/sim/preBPix/GluGlutoHH_kl-1p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_5p00_kt_1p00_c2_0p00: "Run3_2023/sim/preBPix/GluGlutoHH_kl-5p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_0p00_kt_1p00_c2_0p00: "Run3_2023/sim/preBPix/GluGlutoHH_kl-0p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_2p45_kt_1p00_c2_0p00: "Run3_2023/sim/preBPix/GluGlutoHH_kl-2p45_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        # TTG_10_100: "Run3_2022postEE/TTG-1Jets_PTG-10to100.parquet"
        TTG_100_200: "Run3_2023/sim/preBPix/TTG-1Jets_PTG-100to200/nominal/NOTAG_merged.parquet"
        TTG_200: "Run3_2023/sim/preBPix/TTG-1Jets_PTG-200/nominal/NOTAG_merged.parquet"
        # TT: "Run3_2022preEE/TT.parquet"
    postBPix:
        GGJets: "Run3_2023/sim/postBPix/DDQCDGJets/GGJets_high_Rescaled.parquet"
        DDQCDGJET: "Run3_2023/sim/postBPix/DDQCDGJets/DDQCDGJET_Rescaled.parquet"
        TTGG: "Run3_2023/sim/postBPix/TTGG/nominal/NOTAG_merged.parquet"
        ttHtoGG_M_125: "Run3_2023/sim/postBPix/ttHtoGG/nominal/NOTAG_merged.parquet"
        BBHto2G_M_125: "Run3_2023/sim/postBPix/bbHtoGG/nominal/NOTAG_merged.parquet"
        GluGluHToGG_M_125: "Run3_2023/sim/postBPix/GluGluHtoGG/nominal/NOTAG_merged.parquet"
        VBFHToGG_M_125: "Run3_2023/sim/postBPix/VBFHtoGG/nominal/NOTAG_merged.parquet"
        VHtoGG_M_125: "Run3_2023/sim/postBPix/VHtoGG/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_1p00_kt_1p00_c2_0p00: "Run3_2023/sim/postBPix/GluGlutoHH_kl-1p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_5p00_kt_1p00_c2_0p00: "Run3_2023/sim/postBPix/GluGlutoHH_kl-5p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_0p00_kt_1p00_c2_0p00: "Run3_2023/sim/postBPix/GluGlutoHH_kl-0p00_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        GluGlutoHHto2B2G_kl_2p45_kt_1p00_c2_0p00: "Run3_2023/sim/postBPix/GluGlutoHH_kl-2p45_kt-1p00_c2-0p00/nominal/NOTAG_merged.parquet"
        # TTG_10_100: "Run3_2022postEE/TTG-1Jets_PTG-10to100.parquet"
        TTG_100_200: "Run3_2023/sim/postBPix/TTG-1Jets_PTG-100to200/nominal/NOTAG_merged.parquet"
        TTG_200: "Run3_2023/sim/postBPix/TTG-1Jets_PTG-200/nominal/NOTAG_merged.parquet"
        # TT: "Run3_2022preEE/TT.parquet"
    data:
        2022_EraE: "Run3_2022/data/Data_EraE_NOTAG_merged.parquet"
        2022_EraF: "Run3_2022/data/Data_EraF_NOTAG_merged.parquet"
        2022_EraG: "Run3_2022/data/Data_EraG_NOTAG_merged.parquet"
        2022_EraC: "Run3_2022/data/DataC_2022_NOTAG_merged.parquet"
        2022_EraD: "Run3_2022/data/DataD_2022_NOTAG_merged.parquet"
        2023_EraC: "Run3_2023/data/Data_EraD_NOTAG_merged.parquet"
        2023_EraD: "Run3_2023/data/Data_EraC_NOTAG_merged.parquet"

systematics:
- ScaleEB2G_IJazZ_down
- ScaleEB2G_IJazZ_up
- ScaleEE2G_IJazZ_up
- ScaleEE2G_IJazZ_down
- Smearing2G_IJazZ_down
- Smearing2G_IJazZ_up
- jec_syst_Total_down
- jec_syst_Total_up
- jer_syst_down
- jer_syst_up
- FNUF_down
- FNUF_up
- Material_down
- Material_up

# info to save in the parquets
save_all_columns_sim_nominal : True
save_all_columns_data : True
save_all_columns_sim_systematics : False